spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "1425"
    driver-class-name: com.mysql.cj.jdbc.Driver

kakao:
  api:
    key: 748f5ec6acf376dbecc444759629df2c

